name: documentation_builder
description: Generates markdown documentation files from markdown template files.
version: 0.0.1
repository: https://github.com/efficientyboosters/documentation_builder

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.1.0
  build_config: ^1.0.0
  build_runner: ^2.1.2
  test: ^1.17.12
  collection: ^1.15.0
  fluent_regex: ^1.0.0
  http: ^0.13.3
  analyzer: ^1.7.1


