name: documentation_builder
description: Generates markdown documentation files from markdown template files.
version: 0.0.14
repository: https://github.com/domain-centric/documentation_builder
documentation: https://github.com/domain-centric/documentation_builder/wiki

environment:
  sdk: ^3.7.2

dependencies:
  build: ^2.3.1
  build_config: ^1.1.0
  collection: ^1.19.1
  fluent_regex: ^1.0.3
  http: ^1.2.0
  analyzer: ^7.4.4
  logging: ^1.0.2
  template_engine: ^1.5.1
  petitparser: ^6.1.0
  process_run: ^1.2.4
  yaml: ^3.1.3
  resource_portable: ^3.1.2
  
dev_dependencies:
  lints: ^5.1.1
  test: ^1.21.6
  build_runner: ^2.2.1
  shouldly: ^0.5.0+1