name: documentation_builder
description: Generates documentation files that can import other files or Dart documentation comments.
version: 1.0.0
repository: https://github.com/domain-centric/documentation_builder
issue_tracker: https://github.com/domain-centric/documentation_builder/pulls
documentation: https://github.com/domain-centric/documentation_builder/wiki

environment:
  sdk: ^3.8.0

dependencies:
  build: ^2.3.1
  build_config: ^1.1.0
  collection: ^1.19.1
  fluent_regex: ^1.0.3
  http: ^1.2.0
  analyzer: ^7.4.4
  logging: ^1.0.2
  template_engine: ^1.5.2
  petitparser: ^6.1.0
  process_run: ^1.2.4
  yaml: ^3.1.3
  resource_portable: ^3.1.2
  crypto: ^3.0.6
  glob: ^2.1.3
  package_config: ^2.2.0
  yaml_writer: ^2.1.0
  
  
dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.6
  build_runner: ^2.2.1
  shouldly: ^0.5.0+1
  frontend_server_client: ^4.0.0

executables:
  documentation_builder: 

topics:
  - documentation
  - code-generation
  - markdown
  - dart
  - build-system